version: "3"
services:
  database:
    build: ./docker/mysql
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sample
    volumes:
      - ./docker/mysql/sql:/docker-entrypoint-initdb.d
