name: ci
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: sample
          TZ: "Asia/Tokyo"
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v1
      - name: setup golang v1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x
      - name: test
        run: go test -v ./database ./models
        env:
          DATABASE_USER: root
          DATABASE_PASSWORD: root
          DATABASE_HOST: localhost
          DBTABASE_PORT: ${{ job.services.mysql.ports['3306'] }}
          DATABASE_NAME: sample
