on: push
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: sample
        volumes:
          - ./docker/mysql/sql:/docker-entrypoint-initdb.d
          - ./docker/mysql/conf.d:/etc/mysql/conf.d
    steps:
      - uses: actions/checkout@master
      - name: setup golang
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - run: go test -v ./...
        env:
          DATABASE_USER: root
          DATABASE_PASSWORD: root
          DATABASE_HOST: 127.0.0.1
          DATABASE_PORT: ${{ job.services.mysql.ports['3306'] }}
          DATABASE_NAME: sample
